name: poker_with_friends
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.2
  go_router: ^14.0.0
  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  protobuf: ^3.1.0
  web_socket_channel: ^2.2.0

  # If you don't need one of the following dependencies,
  # delete the relevant line below, and get rid of any Dart code
  # that references the dependency.
  firebase_core: ^3.0.0  # Needed for Crashlytics below
  # firebase_crashlytics: ^4.0.0  # Error reporting
  # games_services: ^4.0.0  # Achievements and leaderboards
  # google_mobile_ads: ^5.0.0  # Ads
  # in_app_purchase: ^3.0.1  # In-app purchases

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpg"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/cards/
    - assets/music/
    - assets/sfx/
    - assets/ca/
